services:
  kafka:
    image: confluentinc/cp-kafka:8.0.0
    ports:
      - "${KAFKA_EXTERNAL_PORT:-9093}:9093"
    environment:
      KAFKA_NODE_ID: 1

      # Security & listeners
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_LISTENERS: CONTROLLER://kafka:29093,SASL_PLAINTEXT://kafka:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # What we tell clients
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://kafka:9092,EXTERNAL://${KAFKA_EXTERNAL_HOST:-localhost}:${KAFKA_EXTERNAL_PORT:-9093}

      # SASL Configuration
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN

      # JAAS inline config (single line required)
      KAFKA_LISTENER_NAME_SASL__PLAINTEXT_PLAIN_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_ADMIN_USER}" password="${KAFKA_ADMIN_PASSWORD}" user_${KAFKA_ADMIN_USER}="${KAFKA_ADMIN_PASSWORD}";
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_ADMIN_USER}" password="${KAFKA_ADMIN_PASSWORD}" user_${KAFKA_ADMIN_USER}="${KAFKA_ADMIN_PASSWORD}";

      # Super user
      KAFKA_SUPER_USERS: User:${KAFKA_ADMIN_USER}

      # Required by Confluent image when SASL is enabled
      KAFKA_OPTS: "-Djava.security.auth.login.config=/dev/null"

      # Storage & replication
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      CLUSTER_ID: MhU3OEVBNTcwNTJENDM2Qh
    volumes:
      - data:/var/lib/kafka/data
    networks:
      - backend
    restart: unless-stopped
    logging:
      options:
        max-size: 5m

volumes:
  data:

networks:
  backend:
    name: backend
    external: true
