services:
  kafka:
    image: bitnami/kafka:2-debian-10
    volumes:
      - kafka:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - backend
    restart: always
    logging:
      options:
        max-size: 50m

  zookeeper:
    image: docker.io/bitnami/zookeeper:3-debian-10
    volumes:
      - zookeeper:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - backend
    restart: always
    logging:
      options:
        max-size: 50m

networks:
  backend:
    name: backend
    external: true

volumes:
  kafka:
  zookeeper:
