name: common

services:
  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - ${MOUNT_DATA}:/qdrant/storage
    networks:
      - backend
    ports:
      - ${PORT}:6333
    restart: unless-stopped
    environment:
      - QDRANT__SERVICE__API_KEY=${API_KEY}
    logging:
      options:
        max-size: 5m

networks:
  backend:
    name: backend
    external: true
