services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - ${PORT}:9000
    volumes:
      - ${MOUNT_DATA}:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    logging:
      options:
        max-size: 5m
