services:
  nginx:
    build: .
    networks:
      - backend
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ${MOUNT_DATA}/cache:/cache/nginx
    restart: unless-stopped
    ports:
      - ${PORT}:80
    logging:
      options:
        max-size: 5m

networks:
  backend:
    name: backend
    external: true