services:
  nginx:
    build: .
    image: nginx
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - cache:/cache/nginx
    logging:
      options:
        max-size: 5m

volumes:
  cache:

networks:
  backend:
    name: backend
    external: true
