services:
  kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ./data:/app/data
    ports:
      - 8771:3000
    environment:
      UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN: true
      UPTIME_KUMA_PORT: 3000
    restart: unless-stopped
    networks:
      - backend
    logging:
      options:
        max-size: 5m

networks:
  backend:
    name: backend
    external: true
