services:
  kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ${MOUNT_DATA}:/app/data
    ports:
      - ${PORT}:3001
    environment:
      UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN: true
    restart: unless-stopped
    networks:
      - backend
    logging:
      options:
        max-size: 5m

networks:
  backend:
    name: backend
    external: true
