services:
  kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - data:/app/data
    ports:
      - 8771:3001
    environment:
      UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN: true
    restart: always
    logging:
      options:
        max-size: 50m

volumes:
  data: