services:
  squid:
    image: ubuntu/squid:latest
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./passwd:/etc/squid/passwd
    networks:
      - backend
    ports:
      - ${PORT}:3128
    restart: unless-stopped
    logging:
      options:
        max-size: 5m

networks:
  backend:
    name: backend
    external: true
