services:
  postgres:
    image: postgres:16.3-alpine3.20
    environment:
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}
    volumes:
      - ${MOUNT_DATA}:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - ${PORT}:5432
    restart: unless-stopped
    logging:
      options:
        max-size: 5m

networks:
  backend:
    external: true
