services:
  mongodb:
    image: mongo:7.0.8
    volumes:
      - ${MOUNT_DATA}:/data/db
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    ports:
      - ${PORT}:27017
    restart: unless-stopped
    logging:
      options:
        max-size: 5m

networks:
  backend:
    name: backend
    external: true
