services:
  redis:
    image: redis:8.0.3-alpine
    command:
      ["redis-server", "--appendonly", "yes", "--requirepass", "${PASSWORD}"]
    volumes:
      - ${MOUNT_DATA}:/data
    ports:
      - ${PORT}:6379
    networks:
      - backend
    restart: unless-stopped
    logging:
      options:
        max-size: 5m

networks:
  backend:
    name: backend
    external: true
