services:
  redis:
    image: redis:alpine
    command:
      ["redis-server", "--appendonly", "yes", "--requirepass", "${PASSWORD}"]
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
    networks:
      - backend
    restart: always
    logging:
      options:
        max-size: 50m

networks:
  backend:
    name: backend
    external: true
