services:
  n8n:
    build: .
    ports:
      - ${PORT}:5678
    volumes:
      - ${MOUNT_DATA}:/home/node/.n8n
    environment:
      - WEBHOOK_URL=${WEBHOOK_URL}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    restart: unless-stopped
    networks:
      - backend
    logging:
      options:
        max-size: 5m

networks:
  backend:
    name: backend
    external: true
