services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - ${PORT}:11434
    volumes:
      - ${MOUNT_DATA}:/root/.ollama
    networks:
      - backend
    logging:
      options:
        max-size: 10m

networks:
  backend:
    name: backend
    external: true
